#!/bin/sh
set -e

rootdir=/etc/vm
device="$1"
name="${device#vm-}"
. "$rootdir/utils.sh"

file=$(basename "$name.conf")
conf=$(resolve_includes "$rootdir/conf" "$rootdir/conf/$file")

# Set configuration
while read -r k v ; do
        eval "conf_$k=$v"
done <<EOF
$conf
EOF

if test -e /sys/class/net/"$device" ; then
	ip link del "$device"
fi
