#!/bin/sh
set -e

rootdir=/etc/vm
device="$1"
name="${device#vm-}"
name="${name%-*}"
. "$rootdir/utils.sh"

read_conf "$rootdir" "$name"

ip -6 addr add dev "$device" fe80::1/64 scope link
ip -6 route add "$conf_net_ipv6" dev "$device"
