#!/bin/sh
set -e

rootdir=/etc/vm
device="$1"
name="${device#vm-}"
name="${name%-*}"
. "$rootdir/utils.sh"

# Read files
file=$(basename "$name.conf")
conf=$(resolve_includes "$rootdir/conf" "$rootdir/conf/$file")

# Set configuration
while read -r k v ; do
        eval "conf_$k=$v"
done <<EOF
$conf
EOF

ip -6 addr add dev "$device" fe80::1/64 scope link
ip -6 route add "$conf_net_ipv6" dev "$device"
