#!/bin/sh
set -e

rootdir=/etc/vm
name="$1"
. "$rootdir/utils.sh"

read_conf "$rootdir" "$name"

# Read and expand parameters.
params=$(resolve_includes "$rootdir/include" "$rootdir/machines.d/$file")
params=$(expand "$params")

# Build command line.
set -- qemu-system-x86_64

while read -r k v ; do
        set -- "$@" "-$k"
	if test -n "$v" ; then
		set -- "$@" "$v"
	fi
done <<EOF
$params
EOF

# Setup interface.
tapdev=$("$rootdir/scripts/ifup" "$name" vm-"$name")
test $? -ne 0 && exit 1

# Launch qemu.
exec "$@" 3<>"$tapdev"
