#!/bin/sh

name="$1"
rootdir=/etc/vm

. "$rootdir"/utils.sh

pid=$(getpid "$name")
if test -n "$pid"; then
    echo "error: $name is already running" >&2
    exit 1
fi

mkdir -p /run/vm/"$name"
"$rootdir/scripts/launch" "$name" &
echo $! > /run/vm/"$name"/pid
